// AliasDefAST.java
// This file was generated by AST2J (0.5a) on Thu May 19 17:16:11 JST 2005
// Source: ast2j.ast Version: 1.0 Author: Takuo Watanabe (takuo@acm.org)
package jp.ac.titech.cs.psg.ast2j;
class AliasDefAST extends DefinitionAST {
    private String name;
    private TypeAST type;
    public AliasDefAST (String name, TypeAST type) {
        this.name = name;
        this.type = type;
    }
    public String getName () { return name; }
    public TypeAST getType () { return type; }
    public void accept (ASTVisitor v) {
        v.visitAliasDefAST(this);
    }
}
