// ArrayTypeAST.java
// This file was generated by AST2J (0.5a) on Thu May 19 17:16:11 JST 2005
// Source: ast2j.ast Version: 1.0 Author: Takuo Watanabe (takuo@acm.org)
package jp.ac.titech.cs.psg.ast2j;
class ArrayTypeAST extends TypeAST {
    private TypeAST elem;
    public ArrayTypeAST (TypeAST elem) {
        this.elem = elem;
    }
    public TypeAST getElem () { return elem; }
    public void accept (ASTVisitor v) {
        v.visitArrayTypeAST(this);
    }
}
