// SyntaxDefAST.java
// This file was generated by AST2J (0.5a) on Thu May 19 17:16:11 JST 2005
// Source: ast2j.ast Version: 1.0 Author: Takuo Watanabe (takuo@acm.org)
package jp.ac.titech.cs.psg.ast2j;
class SyntaxDefAST extends DefinitionAST {
    private String name;
    private NodeDefAST[] defs;
    public SyntaxDefAST (String name, NodeDefAST[] defs) {
        this.name = name;
        this.defs = defs;
    }
    public String getName () { return name; }
    public NodeDefAST[] getDefs () { return defs; }
    public void accept (ASTVisitor v) {
        v.visitSyntaxDefAST(this);
    }
}
