// AliasDefAST.java
// This file was generated by AST2J (0.5a) on Mon Jul 24 17:09:48 JST 2017
// Source: ast2j.ast Version: 1.0 Author: Takuo Watanabe (takuo@acm.org)
package jp.ac.titech.c.psg.ast2j;
class AliasDefAST extends DefinitionAST {
    private String name;
    private TypeAST type;
    public AliasDefAST (String name, TypeAST type) {
        this.name = name;
        this.type = type;
    }
    public String getName () { return name; }
    public TypeAST getType () { return type; }
    public void accept (ASTVisitor v) {
        v.visitAliasDefAST(this);
    }
}
