// ASTVisitor.java
// This file was generated by AST2J (0.5a) on Mon Jul 24 17:09:48 JST 2017
// Source: ast2j.ast Version: 1.0 Author: Takuo Watanabe (takuo@acm.org)
package jp.ac.titech.c.psg.ast2j;
abstract class ASTVisitor {
    public abstract void visitAliasDefAST (AliasDefAST n);
    public abstract void visitSyntaxDefAST (SyntaxDefAST n);
    public abstract void visitCNodeDefAST (CNodeDefAST n);
    public abstract void visitANodeDefAST (ANodeDefAST n);
    public abstract void visitFieldDefAST (FieldDefAST n);
    public abstract void visitPrimTypeAST (PrimTypeAST n);
    public abstract void visitArrayTypeAST (ArrayTypeAST n);
}
