// CNodeDefAST.java
// This file was generated by AST2J (0.5a) on Mon Jul 24 17:09:48 JST 2017
// Source: ast2j.ast Version: 1.0 Author: Takuo Watanabe (takuo@acm.org)
package jp.ac.titech.c.psg.ast2j;
class CNodeDefAST extends NodeDefAST {
    private String name;
    private FieldDefAST[] fields;
    public CNodeDefAST (String name, FieldDefAST[] fields) {
        this.name = name;
        this.fields = fields;
    }
    public String getName () { return name; }
    public FieldDefAST[] getFields () { return fields; }
    public void accept (ASTVisitor v) {
        v.visitCNodeDefAST(this);
    }
}
